
-- Create layout_submissions table
CREATE TABLE IF NOT EXISTS public.layout_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    layout_id TEXT NOT NULL,
    image_metadata JSONB NOT NULL DEFAULT '[]',
    license_key TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add RLS
ALTER TABLE public.layout_submissions ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (or restrict by license key API if needed)
-- For now, we'll rely on the API route to handle validation
CREATE POLICY "Enable all for anyone" ON public.layout_submissions FOR ALL USING (true);

-- Add comment
COMMENT ON TABLE public.layout_submissions IS 'Stores layout selections and uploaded image metadata from WordPress.';
