import { PluginEntry } from "@/types/plugin";

export const DUMMY_ENTRIES: PluginEntry[] = [
  {
    id: '1', name: 'Sarah Johnson', profession: 'Creative Director',
    content: 'Passionate about crafting unique visual experiences and leading design teams to excellence. Over 10 years of experience in brand strategy.',
    style: 'Strategic|Branding|UX Design', image_id: 'img1', video_id: 'vid1', c_order: 1, layout: 1,
    s_title: 'Our Experts', s_cont: 'Meet the talented individuals who drive our creative vision.',
    image_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=600&h=800',
    video_url: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '2', name: 'Michael Chen', profession: 'Lead Developer',
    content: 'Full-stack developer with a focus on React, Next.js, and high-performance server architectures.',
    style: 'Full Stack|Next.js|DevOps', image_id: 'img2', video_id: 'vid2', c_order: 2, layout: 1,
    s_title: 'Our Experts', s_cont: 'Meet the talented individuals who drive our creative vision.',
    image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600&h=800',
    video_url: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '3', name: 'Emily Davis', profession: 'Marketing Strategist',
    content: 'Specializing in digital growth and customer engagement. Emily has helped dozens of startups scale.',
    style: 'Growth|Marketing|Strategy', image_id: 'img3', video_id: 'vid3', c_order: 3, layout: 1,
    s_title: 'Our Experts', s_cont: 'Meet the talented individuals who drive our creative vision.',
    image_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=600&h=800',
    video_url: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '4', name: 'Robert Wilson', profession: 'UX/UI Designer',
    content: 'Bridging the gap between aesthetics and functionality. Robert focuses on intuitive interfaces.',
    style: 'Interface|User Journey|Delight', image_id: 'img4', video_id: 'vid4', c_order: 4, layout: 1,
    s_title: 'Our Experts', s_cont: 'Meet the talented individuals who drive our creative vision.',
    image_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600&h=800',
    video_url: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '5', name: 'Lisa Wang', profession: 'Project Manager',
    content: 'Ensuring on-time delivery and seamless communication. Lisa keeps multidisciplinary teams in harmony.',
    style: 'Management|Coordination|Agile', image_id: 'img5', video_id: 'vid5', c_order: 5, layout: 1,
    s_title: 'Our Experts', s_cont: 'Meet the talented individuals who drive our creative vision.',
    image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=600&h=800',
    video_url: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '6', name: 'James Rodriguez', profession: 'Content Creator',
    content: 'Storyteller with a lens for visual narrative. James brings brands to life through compelling media.',
    style: 'Videography|Storytelling|Media', image_id: 'img6', video_id: 'vid6', c_order: 6, layout: 1,
    s_title: 'Our Experts', s_cont: 'Meet the talented individuals who drive our creative vision.',
    image_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=600&h=800',
    video_url: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '7', name: 'Anna Sophie', profession: 'Product Designer',
    content: 'Creating user-centric products that solve real-world problems with elegant solutions.',
    style: 'Product|UX|Design', image_id: 'img7', video_id: 'vid7', c_order: 7, layout: 1,
    s_title: 'Our Experts', s_cont: 'Meet the talented individuals who drive our creative vision.',
    image_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=600&h=800',
    video_url: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '8', name: 'David Miller', profession: 'Backend Engineer',
    content: 'Architecting scalable systems and ensuring data integrity across complex infrastructures.',
    style: 'Backend|Scaling|System', image_id: 'img8', video_id: 'vid8', c_order: 8, layout: 1,
    s_title: 'Our Experts', s_cont: 'Meet the talented individuals who drive our creative vision.',
    image_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=600&h=800',
    video_url: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '9', name: 'Sophia Loren', profession: 'Art Director',
    content: 'Leading creative campaigns with a focus on high-fashion and luxury branding.',
    style: 'Art|Fashion|Luxury', image_id: 'img9', video_id: 'vid9', c_order: 9, layout: 1,
    s_title: 'Our Experts', s_cont: 'Meet the talented individuals who drive our creative vision.',
    image_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=600&h=800',
    video_url: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '10', name: 'Alex Wong', profession: 'Mobile Developer',
    content: 'Building seamless cross-platform mobile experiences for global startups.',
    style: 'Mobile|React Native|Flutter', image_id: 'img10', video_id: 'vid10', c_order: 10, layout: 1,
    s_title: 'Our Experts', s_cont: 'Meet the talented individuals who drive our creative vision.',
    image_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=600&h=800',
    video_url: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '11', name: 'Maria Garcia', profession: 'Data Scientist',
    content: 'Extracting insights from complex data to drive business decisions and innovation.',
    style: 'Data|AI|ML', image_id: 'img11', video_id: 'vid11', c_order: 11, layout: 1,
    s_title: 'Our Experts', s_cont: 'Meet the talented individuals who drive our creative vision.',
    image_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=600&h=800',
    video_url: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
  {
    id: '12', name: 'Tom Hardy', profession: 'Cybersecurity Analyst',
    content: 'Protecting digital assets and ensuring system resilience against modern cyber threats.',
    style: 'Security|Cloud|DevSecOps', image_id: 'img12', video_id: 'vid12', c_order: 12, layout: 1,
    s_title: 'Our Experts', s_cont: 'Meet the talented individuals who drive our creative vision.',
    image_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=600&h=800',
    video_url: 'https://vjs.zencdn.net/v/oceans.mp4',
  },
];
